Implement BugzillaIssueClient.getTotalIssues() function
kovaloid/iresolver pull request #158
Opened 2021-03-13 12:13 UTC by oleg088097

2021-03-14 13:32 UTC, kovaloid requested changes
Let's implement it something like this:
```
@Override
  public int getTotalIssues(final String query) {
    final DefaultSearchData searchData = getSearchDataByQuery(query);
    searchData.add("offset", String.valueOf(0));
    searchData.add("limit", String.valueOf(0));
    AtomicInteger totalIssues = new AtomicInteger();
    session.searchBugs(searchData, totalIssues::set);
    return totalIssues.get();
  }
```
But notice, that it's just a proposal, you need to test it first :)

2021-03-15 19:59 UTC, oleg088097 commented on bugzilla-connector/src/main/java/com/koval/resolver/connector/bugzilla/client/BugzillaIssueClient.java
> +    return this.search(query, 0, 0, Collections.emptyList()).size();
@kovaloid, well, yeah, it works. But please, tell me, why do you want to duplicate code and overcomplicate things?
![image](https://user-images.githubusercontent.com/36167478/111213049-6b580b00-85e1-11eb-974a-59969341b7bb.png)

2021-03-15 20:19 UTC, kovaloid commented on bugzilla-connector/src/main/java/com/koval/resolver/connector/bugzilla/client/BugzillaIssueClient.java
> +    return this.search(query, 0, 0, Collections.emptyList()).size();
It's not so complicated actually :) In short words this is to optimize performance.
Inside the `searchBugs` function, the list of issue ids is formed and an iterator is returned as a result.
Each time the iterator is called, we request the body of the issue.
For-each statement in the `search` function implicitly uses such iterator underhood. 
But we don't need to waste time to get issue bodies.
In this case using callback (the second argument of `searchBugs`) we retrieve only the size of issue ids list.
In terms of execution time it is much more cost-effective operation.

2021-03-15 20:23 UTC, kovaloid approved these changes

2021-03-15 20:33 UTC, merged